name: cd

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build and package the extension
        run: bun run package

      - uses: actions/upload-artifact@v4
        with:
          path: qoa-preview-*.vsix
  release:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-and-package
    permissions:
      contents: write
    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          files: qoa-preview-*.vsix
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
